export const COMMON_ERRORS = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SYSTEM_ERROR: 'SYSTEM_ERROR',
    TOKEN_INVALID: 'TOKEN_INVALID',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND'
};
